config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations:'users/registrations',
        sessions: 'users/sessions'
      }
      

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :albums do
    resources :photos
  end
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user
	has_many :photos, :dependent => :destroy
	validates_length_of :photos, maximum: 25,:too_long  => "must have at most {{count}} words"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  has_attached_file :image
  validates_attachment :image, presence: true,
  content_type: { content_type: "image/jpeg" },
  size: { in: 0..500.kilobytes }
  validates_associated :album
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  validates :first_name, length: {maximum: 100, too_long: "%{count} characters is the maximum allowed"},format: {  :with => /\A[a-zA-Z]+\z/,:message => "is not valid"} ,presence: true
  validates :last_name, length: {maximum: 100, too_long: "%{count} characters is the maximum allowed"},format: {  :with => /\A[a-zA-Z]+\z/, :message => "is not valid"}, presence: true
  validates :email, format: {with: /\A[a-zA-Z\+[0-9]\+\-_\.\+a-z\d]+@[a-z\-.]+\.([a-z]{2,})+\z/i}, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def new
    @album = Album.new
  end
  def index
  	@albums = Album.all
  end

  def create
    @album = Album.new(album_params)
    @album.user_id = current_user.id
    
    if @album.save
      redirect_to albums_path
    else
      render :new
    end
  end
  def destroy
    @album = Album.find(params[:id])
    if @album.destroy 
      redirect_to albums_path
    else
      render :new
    end
  end
  def show
    @album = Album.find params[:id]
  end
  private
  def album_params
   params.require(:album).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@photos = Photo.all
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: :index

  before_filter :set_album
  def index
   @photos = Photo.all
  end
  def show
    @photo = @album.photos.find params[:id]
  end

  def new
    @photo = @album.photos.new
  end

  def create
    @photo = @album.photos.new(photo_params)                 
    @photo.album = @album
    
    if @photo.save
      redirect_to @album
    else
      render :new
    end
  end

  def edit
    @photo = @album.photos.find params[:id]
  end

  def update
    @photo = @album.photos.find params[:id]

    if @photo.update_attributes(photo_params)
      redirect_to @album
    else
      render :edit
    end
  end
  def destroy
    @photo = @album.photos.find params[:id]

    if @photo.destroy
      redirect_to @album
    else
      render :new
    end
  end

  private
  def set_album
    @album = Album.find params[:album_id]
  end
  def photo_params
     params.require(:photo).permit(:tagline_photo,:image)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
   def edit
    super
   end

  # PUT /resource
   def update
    super
  end

  # DELETE /resource
   def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/index.html.erb
<% if user_signed_in? %>
 	<div class="row" >
		<div class= "album_menues">
		  <ul class="list-unstyled ul_menu">
		    <li>
		      <%= link_to "New Album", new_album_path %>
		     </li>
		     <li>
			    <ul class="list-inline ">
			      <li style="margin-left:20px;"> My Albums =>                         
			      </li>
			        <% @albums.each do |album| %>
			          <li>
				          <% if album.user_id == current_user.id %>

							  		<%= link_to album.title, album %>
							  		 <%= link_to "delete", album_url(album), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style:"margin-top: -7px;"%>
							  		 <br>
					  				<% else %>
				  	      <% end%>
				        </li>
				      <% end %>
				  </ul>
			  </li>
		  </ul>
		</div>
  </div>
<% else %>
  <div class="row" >
    <div class= "home_album_menues">
	    <ul class="list-unstyled ul_menu">
			  <% @albums.each do |album| %>
			  <li>
			  <%= link_to album.title, album%>
			  </li>
			  <br>
			  <% end %>
		  </ul>
	  </div>
  </div>
<% end %>

app/views/albums/new.html.erb
<h2 class="heading">New Album</h2>
<div class=" login_form container text-center">
	<%= form_for @album do |f| %>
	  <div>
	    <%= f.label :title,class: "label_font" %> <br>
	    <%= f.text_field :title,:required => true,class: "field"%>
	  </div>
	  <div>
	    <%= f.submit 'Create Album',class: "field btn btn-success", style: "font-size: 20px" %>
	  </div>
	<% end %>
</div>

app/views/albums/show.html.erb
<% if user_signed_in? %>
	<h1><%= @album.title %></h1>
  <div>
		<p>
		 <%= link_to 'Upload new photo', new_album_photo_path(@album) %>
		</p>
		<p>
			<% @album.photos.each do |photo| %>
			  <%= link_to [@album, photo] do %>
			    <div class="row">	
		  			<div class="col-md-4">
					    <div class="thumbnail">
					      <%= image_tag photo.image, class: 'image-size'%>
					    <div>
					      <p class="image-text"><%= photo.tagline_photo %>
					      </p>
						    <p class="image-text">
						      <%= (photo.created_at).strftime("%d/%m/%Y") %>
						    </p>
						    <p class="image-text">
						      <%= User.find_by_id(@album.user_id).first_name %>
						      <%= User.find_by_id(@album.user_id).last_name %>
						    </p>
						    <p class="image-text">
                  <% if current_user.id == @album.user_id %>
						        <%= link_to "delete", album_photo_url(@album,photo), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', style:"margin-top: -7px"%>

						      <% end %>
						      </p>
						    </div>
						  </div>
		        </div>
		      <% end %>
		 <% end %>
		</p>
	</div>
<% else %>
	<% @album.photos.each do |photo| %>
		<%= link_to [@album, photo] do %>
		  <div class="row">	
	  	  <div class="col-md-4">
				  <div class="thumbnail">
				    <%= image_tag photo.image, class: 'image-size'%>
				    <div>
				    <p class="image-text">
				      <%= photo.tagline_photo %>
				    </p>
					  <p class="image-text">
					    <%= (photo.created_at).strftime("%d/%m/%Y") %>
					  <p>
					  <p class="image-text">
					    <%= User.find_by_id(@album.user_id).first_name %>
					    <%= User.find_by_id(@album.user_id).last_name %>
					  <p>
					</div>
				</div>
	    </div>
		<% end %>
	<% end %>
<% end %>

app/views/home/index.html.erb
<div class="row">	
	<% @photos.first(25).each do |photo| %>
	  <div class="col-md-4">
	  	<div class="thumbnail">
			  <%= image_tag photo.image,class: 'image-size' %>
			  <div>
				  <p class="image-text">
				  	<%= User.find_by_id(Album.find_by_id(photo.album_id).user_id).first_name %>
				  	<%= User.find_by_id(Album.find_by_id(photo.album_id).user_id).last_name %>
				  </p>
				  <p class="image-text">
				  	<% album_id = Album.find_by_id(photo.album).id %>
				  	<%= Album.find_by_id(photo.album).created_at.strftime("%d/%m/%Y") %><br/>
				  	<%= link_to Album.find_by_id(photo.album).title, photo.album %>
				  </p>
			  </div>
			</div>
		</div>
	<% end %>
</div>

		  
	

		
		
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoalbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <li><%= link_to "PHOTO GALLARY", root_path,class: "navbar-brand" %>
          </li>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "All albums", albums_path %>
          </li>
            <% if user_signed_in? %>
        		 <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
        		  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      		<% else %>
      		  <li>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
            </li>
            <li>
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
              </li>
      		<% end %>  
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
      
  </body>
</html>

app/views/photos/new.html.erb
<div class=" login_form container text-center">
  <%= form_for [@album, @photo], html: { :multipart => true } do |f| %>
    <div>
      <%= f.label :tagline_photo,class: "label_font" %>
      <br>
    	<%= f.text_field :tagline_photo,:required => true,class: "field" %>
    </div>
    <div>
      <%= f.label :image,class: "label_font"  %>
      <br>
      <%= f.file_field :image ,class: "field",:required => true%>
    </div>
    <div>
      <%= f.submit 'Upload Photo',class: "field btn btn-success", style: "font-size: 20px" %>
      <br>
      or
      <%= link_to 'Cancel', [@album, @photo] %>
    </div>

  <% end %>
</div>

app/views/photos/show.html.erb
<!--<%= link_to 'Edit', edit_album_photo_path(@album, @photo) %> -->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name),class: "label_font" %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) ,class: "label_font"%><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name),class: "label_font" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>